# Generated by Django 3.2.9 on 2021-11-17 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(db_index=True, max_length=255, verbose_name="Kategoriya nomi (O'zbek tilida)")),
                ('name_ru', models.CharField(db_index=True, max_length=255, verbose_name='Kategoriya nomi (Rus tilida)')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name="Sahifa nomi (O'zbek tilida)")),
                ('title_ru', models.CharField(max_length=255, verbose_name='Sahifa nomi (Rus tilida)')),
                ('image', models.ImageField(upload_to='news/%Y/%m')),
                ('description_uz', models.TextField(verbose_name="Sahifa nomi (O'zbek tilida)")),
                ('description_ru', models.TextField(verbose_name='Sahifa nomi (Rus tilida)')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False, null=True)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer')),
            ],
            options={
                'verbose_name': 'Yetkazib berish',
                'verbose_name_plural': 'Yetkazib berishlar',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home_number', models.CharField(blank=True, max_length=255, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order')),
            ],
            options={
                'verbose_name': 'Yetkazib berish manzili',
                'verbose_name_plural': 'Yetkazib berish manzillari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255, verbose_name="Mahsulot nomi (O'zbek tilida)")),
                ('name_ru', models.CharField(max_length=255, verbose_name='Mahsulot nomi (Rus tilida)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Mahsulot haqida')),
                ('description_ru', models.TextField(blank=True, verbose_name='Mahsulot haqida')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m')),
                ('price', models.IntegerField(verbose_name="Narxi (so'mda)")),
                ('qty_uz', models.CharField(max_length=20, verbose_name="O'lchov birligi (O'zbek tilida)")),
                ('qty_ru', models.CharField(max_length=20, verbose_name="O'lchov birligi (Rus tilida)")),
                ('stock', models.IntegerField(default=0, verbose_name='Chegirma foizi')),
                ('is_stock', models.BooleanField(default=False, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
            options={
                'verbose_name': 'Yetkazib beriladigan mahsulot',
                'verbose_name_plural': 'Yetkazib beriladigan mahsulotlar',
            },
        ),
    ]
