# Generated by Django 3.2.9 on 2021-11-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_uz',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_uz',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qty_uz',
            new_name='qty',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qty_ru',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name="Mahsulot haqida (O'zbek tilida)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m', verbose_name='1-Rasm (Majburiy)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m', verbose_name='2-Rasm (Majburiy emas)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m', verbose_name='3-Rasm (Majburiy emas)'),
        ),
    ]
